---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarunlablel
  labels:
    app: tarunlablel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarunlablel
  template:
    metadata:
      labels:
        app: tarunlablel
    spec:
      containers:
      - name: taruncontainer
        image: ttiwari1005/dockerapp:11
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tarunlablel
  labels:
    app: tarunlablel
spec:
  selector:
    app: tarunlablel
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8080
---
